# Generated by Django 5.1.7 on 2025-05-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='#007BFF', help_text='Hex color code (e.g., #ff0066)', max_length=7),
        ),
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='visual_primary_color',
            field=models.CharField(default='#3399FF', help_text='Hex color code', max_length=7),
        ),
        migrations.AddField(
            model_name='product',
            name='visual_secondary_color',
            field=models.CharField(default='#003366', help_text='Hex color code', max_length=7),
        ),
    ]
